artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://raw.githubusercontent.com/Digvijay25/Datasets/refs/heads/main/WineQT.csv
  local_data_file: artifacts/data_ingestion/data